### ISSUE TITLE
add monitoring functionality

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1533]
- [ ] all of the following should work both as log file for triggering external SIEM systems (e.g. splunk) and stand-alone via alert in FWO UI
- [ ] run auto-discovery via scheduler every day (no need for scheduler frontend here, config setting with "run every x hours" is enough
- [ ] alert on every single change (difference between devices in system and discovered)
- [ ] alert on every (serious) import error
- [ ] alert on missing successful import for a management within x hours

**Comment by tpurschke** [comment]
done
