### ISSUE TITLE
Importer: Check Point - inline layers

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#191]
## design

- layer handling (domain/global rules, sections, inline layer)
  - displaying policies as similiar to CP UI as possible
  - store the rule/(sub-)policy data in DB
  - allow for correct interpretation of rule parsing in all modules (starting with filtering)
  - make sure the layers get sorted out correctly (layer in layer vs. two layers on the same level)
  - --> defining relations (owner/app/rule) in separate table see issue #885
- parse inline layers (action='inner layer'), show access rulebase <ruleUID> (see <https://community.checkpoint.com/t5/API-CLI-Discussion-and-Samples/show-access-rulebase-along-with-inline-layers/td-p/33199>); example:

        show access-rulebase uid be146170-a996-47c8-acfd-2b7dfb9e6d0f use-object-dictionary true  --format json
  - decide how to represent this tree structure of layers/rulebases in the database
  - find out how layer guards are defined and how to represent them in the DB
  - decide how to show access-layers in UI (simply concatenate and show as a single policy?)
  - decide how to show inline layers in UI (simply as sections?)
  - decide how to deal with shared layers (simply duplicate and treat as separate?)
  - decide how to treat layer guards (simply ignore logic for the time being?)

## Docs
- <https://sc1.checkpoint.com/documents/R80/APIs/#gui-cli/show-access-layer%20>
- <https://github.com/CactuseSecurity/firewall-orchestrator/blob/master/test/importer/CP-R8x/iso_cp_r8x_api_get_layer_names.py>

## Recipe
- use "show-packages" cmd to get all packages including their access-layers 
- use "show access-layers" cmd to list all layer names/ids
- use "show access-layer" cmd to list a single layer and its parent rule
- use show access-rulebase to display inline layer

## prerequisites
- [x] make sure parent rule is imported before child, otherwise stored procedure insert_single_rule is not working correctly  
- [x] reflect layer structure in database (to be able to display rules correctly, e.g. rule numbers)

## basic features
- [x]  #911
- [x] allow multiple firewall layers (e.g. application
- [x] allow for multiple packages of a management having the same layer names --> work with UIDs instead?
- [x] how to we get the correct order of layers via API (if order is relevant at all)? https://fwmgmt/web_api/show-access-layers has 
- [x] display layer brackets correctly (start and end of layer must be visible)

## advanced features
- [ ] add semantic logic
    - [ ] layer guard and rules within layer need to "anded"
    - [ ] layer clean-up rule only valid within layer
    - [ ] allow for non-blocking clean-up rules which result in continuing the rule base
- [ ] make sure the scenarios "multiple gateways with the same package/layer" are covered (especially in auto-discovery) - avoid processing the same data x times for each gateway? --> would need to introduce an extra table between rule and device rule_gw
- [x] second reference (in sting prod gw) to inline layer in other rulebase (sting-test) is not resolved correctly without sting-test-gw being imported.
- [ ] how to logically link layer guard with rules in layer? --> AND of src, dst & svc between layer guard and each rule in layer?
- [x] add is-inline-layer bool switch to rule table
