### ISSUE TITLE
UI: complete multi-lingual UI German/English

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#370]
for now: use English text in UI
before going public:
- [x] add texts for German & English to DB txt table
- [x] replace all static texts with API calls (including error messages)
- [x] translate help pages (and tooltips?)
- [ ] fix issue with help pages being displayed in default language only (UI restart required after changing default language setting) --> moved to #1095
