### ISSUE TITLE
Autodiscovery Top-level Issue

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#390]
When moving to Python Main Import, add auto discovery for multi domain manager:
- [x] extend database by MDM table, also allowing for exclusions (never import certain domains)
- [x] where can we find the information which layer is the top one for a package?
- [x] R80.20 get device/layer info from API and display it for manual entering in UI
- [x] R80.40 get device/layer info from API and display it for manual entering in UI (layer info missing) - was actually a permission issue
- [x] debug cannot be deactivated (-d 0)
- [x] check if domain filter works (-D xxx)
- [x] have 2 types of autodiscovery: detect and adjust
- [x] #1514
- [x] make changes to database via API (in do not import mode)
- [x] notify admins (notice in UI? or send mail, need to have admin email address) --> see #1533 
- [x] #1539
- [x] disable deletion of multi-domain manager without error: "Management löschen - Nicht klassifizierter Fehler: : Foreign key violation. update or delete on table "management" violates foreign key constraint "management_multi_device_manager_id_fkey" on table "management";  alternatively: add delete cascade? - but do not make this available via UI?
- [x] update help pages
- [x] AutoDiscovery "AddGatewayToExistingManagement" alert does not contain name of missing gateway

**Comment by tpurschke** [comment]
done
