### ISSUE TITLE
UI Report Filter enhancements

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#532]
- [x] point in time filter missing case: if reportTime > last import, take the rules from the last successul import (max), simply add condition changes_found?
- [ ] add cidr filtering ipv6
- [x] add active /inactive filter for rules (enabled/disabled)
- [ ] add cidr filtering ip ranges
- [ ] add src_or_dst_ip filter keywords for both src & dst filter
- [ ] uid filtering
- [ ] add generic action:[block|pass] to filter for all blocking/passing actions
- [ ] add <, <=, >, >= operators for changes report time filter
- [ ] add <, <=, >, >= operators for port filter
- [x] #2278
