### ISSUE TITLE
ui report statistics - various fixes and extensions

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#600]
#### Fixes

- [ ] differentiate between access and nat rules (currently all rules are counted which might cause a raised eyebrow when comparing 1482 rules in statistics report just with the 756 rules in the (standard) access rule report)
- [ ] differentiate between used, unused and total number of objects (services, network objects, users, ...)
- [ ] statistics report shows all gateways of a mgmt if any gw for a mgmt was selected
- [ ] Hide filter line textbox

#### Extensions
add statistics reporting:
- [ ] make gateway table sortable (especially by #rules)
- [x] #2254
- [ ] #3807
- [ ] number of managements & gateways
- [ ] number of managements & gateways per manufacturer
- [ ] overall number of active network/service/user objects
- [ ] number of all/rule/object changes overall, during last month, last year, this month, this year
- [ ] add app modelling statistics as follows:
```graphql
query getAppStatistics {
  totalActiveApps: owner_aggregate(where: {active: {_eq: true}}) {
    aggregate {
      count
    }
  }
  appsWithIps: owner_aggregate(where: {active: {_eq: true}, owner_networks_aggregate: {count: {predicate: {_gt: 0}}}}) {
    aggregate {
      count
    }
  }
  totalCommonSvcApps: owner_aggregate(where: {active: {_eq: true}, common_service_possible: {_eq: true}}) {
    aggregate {
      count
    }
  }
  totalModelledConnections: modelling_connection_aggregate {
    aggregate {
      count
    }
  }
  modelledStandardConnections: modelling_connection_aggregate(where: {is_interface: {_eq: false}, common_service: {_eq: false}}) {
    aggregate {
      count
    }
  }
  modelledInterfaces: modelling_connection_aggregate(where: {is_interface: {_eq: true}}) {
    aggregate {
      count
    }
  }
  modelledComSvcs: modelling_connection_aggregate(where: {common_service: {_eq: true}}) {
    aggregate {
      count
    }
  }
}
```
