### ISSUE TITLE
update: add in-ui update function

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#767]
- [ ] prepare by starting with ansible version that fetches current stable version as first install step via git pull
- [ ] allow checking for new versions and updating via settings UI; would need to call ansible from within C#?
- [ ] also show availability of new stable versions for admin role users in UI
