### ISSUE TITLE
Implement matrix compliance reporting

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#876]
- [x] depends on working CIDR filtering
- [x] UI start with separate top-level UI "Compliance" item
- [x] UI for single zone definition (name, hierarchy, CIDR subnets)
- [x] UI for defining inter-zone rules
- [x] allow for at least two levels of zone hierarchies (area/zone) - could also be implemented as separate matrices?!
- [x] compliance rules to be defined on both levels
- [x] only CIDR-based access matrix taken into consideration
- [x] disable "Configuration Add - OK" and "Matrix - Commit Changes" buttons for all but admin role
- [x] #2424
- [x] add explicit Internet Zone dynamically calculated as all Public IP addresses Not defined in any Zone
- [x] add "private unused" Zone 
- [ ] add help Pages
- [ ] offer option to check all rulebases (but no rulebase should be checked twice) --> requirement for #2477
- [ ] add help Page Info for adding Matrix Data via API
- [ ] sort ip ranges in Configuration page
- [x] double-check completeness of compliance violation list
![Screenshot from 2023-07-25 16-10-49](https://github.com/CactuseSecurity/firewall-orchestrator/assets/19877770/a5cc7726-dcd5-4971-815f-bbdeff7eb61a)
![Screenshot from 2023-07-25 16-10-37](https://github.com/CactuseSecurity/firewall-orchestrator/assets/19877770/0cad7286-29c5-43d1-9563-a7c75ba17f0b)
![Screenshot from 2023-07-25 16-10-10](https://github.com/CactuseSecurity/firewall-orchestrator/assets/19877770/00ca57f5-a4b8-4787-aa68-adcad921bb78)
after upgrading fwodemo.cactus.de to v7.0, the check result is as expected:
![Screenshot from 2023-07-26 19-57-05](https://github.com/CactuseSecurity/firewall-orchestrator/assets/19877770/a2fc2405-e949-486a-a01d-d2516378d9f2)

#### advanced
- [x] allow for multiple named matrices
- [x] add Compliance Report: show all rules that violate compliance matrix (optionally filtered by gateways)
- [x] allow for service filtering (not implementing in the first phase)
- [ ] also add IP V6 addresses for Internet Zone
- [x] make sure that each rulebase is only checked once (if that is customer concensus) so as to not report each rule multiple times
- [x] decide how to choose scope (rulebases vs. Gateways)
- [x] add types: rule Compliance, object compliance ...
- [ ] use Compliance Check: Report, Workflow (Check requested Access), also offer API Call for a single flow and for full Rules
- [ ] Same mimic for traffic Simulation query

**Comment by alf-cactus** [comment]
Design for Compliance Analysis is here
https://xfer.cactus.de/index.php/s/nbene7RToizCe3Y
